CREATE TABLE IF NOT EXISTS results
(
    id INTEGER PRIMARY KEY,
    index INTEGER NOT NULL,
    result VARCHAR(105) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS id_generator START WITH 1 INCREMENT BY 1;
